DROP TABLE IF EXISTS users cascade;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  dob DATE NOT NULL
);

DROP TABLE IF EXISTS tracking;

CREATE TABLE tracking (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  rhr INTEGER,
  mhr INTEGER,
  bps INTEGER,
  bpd INTEGER,
  bls INTEGER,
  ins INTEGER,
  lbs INTEGER,
  cal INTEGER,
  fat INTEGER,
  car INTEGER,
  fib INTEGER,
  pro INTEGER,
  stp INTEGER,
  slp INTEGER,
  act TEXT,
  men TEXT,
  dia TEXT,
  tracking_date DATE DEFAULT now(),
  CONSTRAINT tracking_fk
    FOREIGN KEY(user_id)
      REFERENCES users(id)
);

DROP TABLE IF EXISTS articles;

DROP TYPE IF EXISTS genre;

CREATE TYPE genre AS ENUM ('Fitness', 'Nutrition', 'Metrics');

CREATE TABLE articles(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  topic genre NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT,
  article_date TIMESTAMPTZ DEFAULT now()
);

DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  article_id INTEGER NOT NULL,
  comment TEXT NOT NULL,
  comment_date TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT user_comments_fk
    FOREIGN KEY(user_id)
      REFERENCES users(id),
  CONSTRAINT article_comments_fk
    FOREIGN KEY(article_id)
      REFERENCES articles(id)
);